# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-11445674-1a11-438f-bbf7-af37b5363402";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."luks-11445674-1a11-438f-bbf7-af37b5363402".device = "/dev/disk/by-uuid/11445674-1a11-438f-bbf7-af37b5363402";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-11445674-1a11-438f-bbf7-af37b5363402";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/127b1679-56e6-4a5e-bbb5-62d5f1136890";
#      fsType = "ext4";
#    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CC2D-62C6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
